### ISSUE TITLE
Multiple solutions don't work under Windows

### ISSUE THREAD

**Issue by Engelberg** [tanders/clojure2minizinc#1]
Neither num-solutions nor all-solutions? work under Windows.  Either way, it only displays a list containing one solution for the sample on the main README page.
I have verified that the correct command is being generated and the correct (multiple) solutions are returned, so the problem must be in the parsing of the output string back into a Clojure data structure.

My guess is that the \r\n Windows linebreak is screwing up whatever parsing you are doing on the string.

**Comment by tanders** [comment]
Thanks for your report. Should be fixed now. Apologies for the delay.
